// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjhbhsuflhlanmqhitqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqaGJoc3VmbGhsYW5tcWhpdHFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NjQ2NzcsImV4cCI6MjA3MDU0MDY3N30.k1RWxZ8XjoeTNpK-PgxE8OB1S6d63mbjKS8Qyp6n6gM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});